package types

type ReqType int32

const (
	REQ_TYPE_GET ReqType = iota
	REQ_TYPE_PUT
	REQ_TYPE_HAS
	REQ_TYPE_DEL
	REQ_TYPE_FLUSH
	REQ_TYPE_BATCH_NEW
	REQ_TYPE_BATCH_PUT
	REQ_TYPE_BATCH_DEL
	REQ_TYPE_BATCH_WRITE
	REQ_TYPE_BATCH_RESET
	REQ_TYPE_BATCH_CLOSE
	REQ_TYPE_ITER_NEW
	REQ_TYPE_ITER_NEXT
	REQ_TYPE_ITER_KEY
	REQ_TYPE_ITER_VAL
	REQ_TYPE_ITER_ERROR
	REQ_TYPE_ITER_CLOSE
	REQ_TYPE_SNAP_NEW
	REQ_TYPE_SNAP_HAS
	REQ_TYPE_SNAP_GET
	REQ_TYPE_SNAP_RELEASE
)
